development:
  adapter: postgresql
  database: adorable_trello_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: adorable_trello_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: adorable_trello_production
  pool: 5
  timeout: 5000
